# coffee-web-app/src/main/resources/application.yml

server:
  port: 8081 # 独有端口

spring:
  application:
    name: coffee-app # 独有应用名
  config:
    import:
      - optional:classpath:common-config.yml # 核心：导入通用配置