spring:
  ai:
    vectorstore:
      redis:
        uri: redis://:123456@localhost:6379
        prefix: "coffee:doc:"        #  Redis键名前级，用于区分不同应用的向量数据
        initialize-schema: true #启动时自动创建Redis向量索引结构(首次部署需开启)
        index: coffee-product-index  # #Redis向量索引名称
    dashscope:
      api-key: sk-d12328830ae845e6a8984db9d28fba1f         # 阿里云 DashScope API Key
      # 默认使用 qwen-turbo 或 qwen-plus，无需额外配置 base-url
    memory:
      redis:
        host: 192.168.248.128
        port: 6379
        password: 123456
        timeout: 1800000
  data:
    redis:
      host: 192.168.248.128
      port: 6379
      password: 123456
      timeout: 1800000